#!/usr/bin/env python3
"""OpenAI-compatible Python client for testing the Agent Gateway."""

import argparse
import os
import sys
from typing import Any

try:
    from openai import OpenAI
except ImportError:
    print("Missing dependency: install with `python3 -m pip install openai`", file=sys.stderr)
    raise SystemExit(1)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Test agent-gateway with the OpenAI Python SDK.")
    parser.add_argument(
        "--api",
        choices=("chat", "responses"),
        default=os.getenv("AGW_OPENAI_API", "chat"),
        help="OpenAI API surface to test.",
    )
    parser.add_argument(
        "--base-url",
        default=os.getenv("AGW_BASE_URL", "http://127.0.0.1:8080/v1"),
        help="Gateway OpenAI-compatible base URL.",
    )
    parser.add_argument(
        "--api-key",
        default=os.getenv("AGW_API_KEY", ""),
        help="Local Agent Gateway API key. Sent as Authorization: Bearer <key>.",
    )
    parser.add_argument(
        "--model",
        default=os.getenv("AGW_MODEL", "gpt-4.1"),
        help="Model allowed by the gateway LLM route.",
    )
    parser.add_argument(
        "--prompt",
        default="用一句中文回答：2 + 2 等于几？",
        help="User prompt to send.",
    )
    parser.add_argument(
        "--system",
        default=os.getenv("AGW_SYSTEM_PROMPT", ""),
        help="Optional system prompt. Disabled by default for broad provider compatibility.",
    )
    parser.add_argument(
        "--stream",
        action="store_true",
        help="Test streaming chat completions.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=float(os.getenv("AGW_TIMEOUT", "30")),
        help="Client timeout in seconds.",
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=int(os.getenv("AGW_MAX_TOKENS", "128")),
        help="Maximum output tokens for the request.",
    )
    return parser.parse_args()


def print_response_output(resp: Any) -> None:
    output_text = getattr(resp, "output_text", None)
    if output_text:
        print(output_text)
        return

    for item in getattr(resp, "output", []) or []:
        if getattr(item, "type", "") != "message":
            continue
        for part in getattr(item, "content", []) or []:
            text = getattr(part, "text", None)
            if text:
                print(text)


def run_chat_completions(client: OpenAI, args: argparse.Namespace, messages: list[dict[str, Any]]) -> int:
    request = {
        "model": args.model,
        "messages": messages,
        "max_tokens": args.max_tokens,
    }
    if not args.model.startswith("gpt-5"):
        request["temperature"] = 0.2

    if args.stream:
        print(f"Streaming chat completion (timeout={args.timeout}s, max_tokens={args.max_tokens}):")
        stream = client.chat.completions.create(**request, stream=True)
        for chunk in stream:
            if not chunk.choices:
                continue
            delta = chunk.choices[0].delta
            if delta and delta.content:
                print(delta.content, end="", flush=True)
        print()
        return 0

    print(f"Requesting chat completion (timeout={args.timeout}s, max_tokens={args.max_tokens})...")
    completion = client.chat.completions.create(**request)
    print(completion.choices[0].message.content)
    if completion.usage:
        print(f"usage: {completion.usage}")
    return 0


def run_responses(client: OpenAI, args: argparse.Namespace, messages: list[dict[str, Any]]) -> int:
    request = {
        "model": args.model,
        "input": messages,
        "max_output_tokens": args.max_tokens,
    }

    try:
        responses_api = client.responses
    except AttributeError:
        print("This OpenAI SDK does not expose client.responses; upgrade with `python3 -m pip install -U openai`.", file=sys.stderr)
        return 1

    if args.stream:
        print(f"Streaming response (timeout={args.timeout}s, max_output_tokens={args.max_tokens}):")
        stream = responses_api.create(**request, stream=True)
        for event in stream:
            if getattr(event, "type", "") == "response.output_text.delta":
                print(getattr(event, "delta", ""), end="", flush=True)
        print()
        return 0

    print(f"Requesting response (timeout={args.timeout}s, max_output_tokens={args.max_tokens})...")
    resp = responses_api.create(**request)
    print_response_output(resp)
    if getattr(resp, "usage", None):
        print(f"usage: {resp.usage}")
    return 0


def main() -> int:
    args = parse_args()
    if not args.api_key:
        print("AGW_API_KEY is required because virtual key values are generated by the gateway.", file=sys.stderr)
        return 1
    client = OpenAI(api_key=args.api_key, base_url=args.base_url, timeout=args.timeout, max_retries=0)

    messages = []
    if args.system:
        messages.append({"role": "system", "content": args.system})
    messages.append({"role": "user", "content": args.prompt})
    if args.api == "responses":
        return run_responses(client, args, messages)
    return run_chat_completions(client, args, messages)


if __name__ == "__main__":
    raise SystemExit(main())
